### ekf config file ###
ekf_node:
    ros__parameters:
  
        frequency: 30.0
        use_sim_time: true

        two_d_mode: true

        publish_acceleration: true

        publish_tf: true

        map_frame: map              
        odom_frame: odom            
        base_link_frame: Robo_car  
        world_frame: odom           

        odom0: odom
        odom0_differential: false
        odom0_relative: false
        odom0_queue_size: 50
        odom0_config: [false, false, false,
                      false, false, false,
                      true, true, false,
                      false, false, true,
                      false, false, false]

        imu0: imu
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 50
        imu0_remove_gravitational_acceleration: true
        imu0_config: [false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, true,
                      false, false, false]