# controller_server:
#   ros__parameters:
#     FollowPath.vx_max: 1.5     
#     FollowPath.vy_max: 1.0     
#     FollowPath.wz_max: 2.0     

# local_costmap:
#   local_costmap:
#     ros__parameters:
#       update_frequency: 5.0
#       publish_frequency: 2.0

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       update_frequency: 1.0
#       publish_frequency: 1.0


local_costmap:
  ros__parameters:
   
    robot_base_frame: "base_link"
    global_frame: "odom"
    width: 1.0               
    height: 1.0          
    resolution: 0.05         

   
    update_frequency: 5.0
    publish_frequency: 2.0

    rolling_window: true

    observation_sources: laser_scan_sensor
    laser_scan_sensor: 
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0
      obstacle_range: 2.5
      raytrace_range: 3.0

    # Footprint (example: rectangle)
    footprint: [[-0.25, -0.2], [-0.25, 0.2], [0.25, 0.2], [0.25, -0.2]]
    inflate_radius: 0.1

    # Layers
    plugins:
      - {name: static_layer, type: "nav2_costmap_2d::StaticLayer"}
      - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}
